import { NextResponse } from 'next/server';
import { GoogleGenAI } from '@google/genai';

export const maxDuration = 60; // Allow 60 seconds for Imagen 4.0 generation on Vercel

export async function GET(req: Request) {
    try {
        const { searchParams } = new URL(req.url);
        const prompt = searchParams.get('prompt');

        if (!prompt) {
            return new NextResponse('Prompt is required', { status: 400 });
        }

        // Initialize Gemini AI client
        const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY as string });

        // Generate high-quality 8k image natively
        const response = await ai.models.generateImages({
            model: 'imagen-4.0-generate-001',
            prompt: prompt + ' photorealistic premium luxury 8k resolution highly detailed',
            config: {
                numberOfImages: 1,
                outputMimeType: 'image/jpeg',
                aspectRatio: '1:1',
            }
        });

        const base64Image = response.generatedImages?.[0]?.image?.imageBytes;

        if (!base64Image) {
            throw new Error("No image generated by the AI");
        }

        const buffer = Buffer.from(base64Image, 'base64');

        return new Response(buffer as any, {
            status: 200,
            headers: {
                'Content-Type': 'image/jpeg',
                'Cache-Control': 'public, max-age=31536000, immutable',
            },
        });

    } catch (error: any) {
        console.error('Imagen API Error:', error);
        return new NextResponse(JSON.stringify({ error: error.message || 'Image Generation Failed' }), {
            status: 500,
            headers: { 'Content-Type': 'application/json' },
        });
    }
}
